### ISSUE TITLE
roosterteeth.com Not Loading

### ISSUE THREAD

**Issue by crypticspaghetti** [samuelmaddock/metastream#105]
Working playback controls:
- [x] Play/pause
- [x] Seek
- [x] Volume

Test URLs:
https://roosterteeth.com/episode/gameplay-2019-mega251

This website has stopped working since the transition to the webapp. It was kind of wonky (screen resizing acting up) in the Electron app, but it was workable. Now it just shows a blank screen.
![brave_cu0JhiG2By](https://user-images.githubusercontent.com/3066591/57985214-f423b100-7a21-11e9-8e22-84631bd8efbb.png)

**Comment by samuelmaddock** [comment]
This website works very well for me. Which browser are you using? Could you try in another supported browser or try disabling other extensions you may have installed?

![2019-05-19_13-21-37](https://user-images.githubusercontent.com/1656324/57985653-1aa11680-7a39-11e9-8495-b6b7e8ead497.png)

**Comment by crypticspaghetti** [comment]
I grabbed Google Chrome and it works fine on there.

I am primarily using Brave which is using Chromium: 74.0.3729.157. I have TamperMonkey, and the Metastream extensions installed.

Checking the console gave a couple errors:
![image](https://user-images.githubusercontent.com/3066591/57986497-f80bff00-7a32-11e9-9fbe-b38d30b56495.png)
Errors are the same with Tampermonkey enable and disabled.

I have no problem switching to Chrome for Metastream as I was running the Electron app before anyways, but it may be looking into?

**Comment by samuelmaddock** [comment]
@crypticspaghetti Brave requires changing shield settings on app.getmetastream.com to allow 3rd-party cookies.

![2019-05-19_15-02-21](https://user-images.githubusercontent.com/1656324/57986776-2c89b600-7a47-11e9-8ead-11abd3dcf04c.png)

**Comment by crypticspaghetti** [comment]
Fantastic, works even better than it did in the Electron app!

Thanks for your time.
