### ISSUE TITLE
Add the ability to put URLs to images as profile icons

### ISSUE THREAD

**Issue by LavenderTheGreat** [samuelmaddock/metastream#106]
Just the idea of the ability to set a URL to a PNG or other image as an icon, maybe use OAuth with various services to retrieve icons from those services which are probably more secure.

**Comment by samuelmaddock** [comment]
There are issues around hot linking images and sizing. For example, using a URL could allow someone to use a 5MB+ image as their avatar, incurring network load times on everyone in a session.

I have ideas for locally processing images which I'll probably look into in the future.

**Comment by samuelmaddock** [comment]
Going to close in favor of #152

**Comment by kathelynn** [comment]
use something like gravatar i think. if it will affect everyone's network then allow everyone to change their settings to disable.
