### ISSUE TITLE
DCUNIVERSE.com and Watchcartoononline.com as website i want to add to be supported

### ISSUE THREAD

**Issue by Jack3dragon** [samuelmaddock/metastream#110]
Working playback controls:
- [x] Play/pause
- [x] Seek
- [ ] Volume

Test URLs:

**Comment by samuelmaddock** [comment]
I looked into both.

dcuniverse.com had an issue with the initial seek upon loading the video, this should be fixed in the next update.

watchcartoononline.com blocks loading from an embedded website and won't be possible to support unless they reduce this restriction.
