### ISSUE TITLE
Netflix Playback issue

### ISSUE THREAD

**Issue by TacticianLyra** [samuelmaddock/metastream#111]
Was attempting to play an episode of The Dragon Prince, and one person involved was only seeing a preview image instead of the episode.

**Comment by samuelmaddock** [comment]
The other person needs to be logged in to Netflix as well.

**Comment by TacticianLyra** [comment]
We were all logged in. We were also consistently getting a "Multiple Netflix Tabs" error when no other tabs were open.

**Comment by samuelmaddock** [comment]
@TacticianLyra which browsers were you using?

The multiple tab error is a Netflix issue. You can press the reload button in Metastream a few times and it will eventually work.

**Comment by TacticianLyra** [comment]
Google Chrome. The person unable to see the stream was using Chrome on a Chromebook.

**Comment by SuweyStreams** [comment]
I was having a problem where it wouldn't work with Firefox, but worked fine on Chrome.

**Comment by samuelmaddock** [comment]
There are a few issues with Netflix at the moment.

- "Refused to connect" error: see #135
- Multiple open tabs error: press the reload button in the playback bar after a few seconds.
- Firefox Netflix error: open the developer tools and reload, there's a race condition here i'm still trying to fix.
