### ISSUE TITLE
Issue with Crunchyroll?

### ISSUE THREAD

**Issue by SunsetSubstory** [samuelmaddock/metastream#113]
Hello! I was attempting to watch some shows on Crunchyroll with a friend, and every time I try to play any show, the picture is offset into the corner, as shown in the screenshot. 

![MS ](https://user-images.githubusercontent.com/51038001/58376554-8b659880-7f3b-11e9-8298-4c91b93cd317.png)

We're both on Google Chrome, we've both updated to the latest version, and we're both signed into my account. It was working normally last week right after we both updated.

**Comment by samuelmaddock** [comment]
Welp, I think I broke it. I'll look into it, thanks for reporting.

**Comment by SunsetSubstory** [comment]
I appreciate it, and thank you for your hard work!

**Comment by samuelmaddock** [comment]
I have a fix ready, but I'm going to wait until tomorrow when I have more time for testing to deploy the changes. cd0d72bb9dccafc6cdff5a4687d43789768d157f

**Comment by samuelmaddock** [comment]
@SunsetSubstory Unfortunately the Chrome extension update is stuck in review. It may take a couple hours or a few days. You can use Firefox now if you'd like though.
