### ISSUE TITLE
Volume slider periodically has no effect on Netflix content

### ISSUE THREAD

**Issue by g859** [samuelmaddock/metastream#12]
## Steps to Reproduce:

1. Load any Netflix content 
2. Attempt to adjust the volume through Metastream UI
3. If volume cannot be changed, start a new session and try again [should work]

**Comment by samuelmaddock** [comment]
Try using the Reload button to refresh the webpage. That should work without requiring you to recreate a session.

![metastream_2018-09-14_22-07-43ucyn](https://user-images.githubusercontent.com/1656324/45581372-bfe06b00-b86a-11e8-831a-9a45880dd116.png)

As for why this is happening, I think the script being injected into the page to control media is too slow. I have an idea for how to fix this in the future by inlining the script.
