### ISSUE TITLE
Webcam feature

### ISSUE THREAD

**Issue by AskMeAboutMyPotato** [samuelmaddock/metastream#127]
I am sure you guys know that rabbit will be shutting down and may be starting to experience an influx of users, but I would like to forward an idea that rabb.it had that may be nice. Part of the rabbit UI was that the profile pictures of everyone was visible to everyone during the stream, there was also an option to allow the user's profile picture to show up as a live video feed via some webcam. Me and my friends liked this feature as it made the experience of watching videos together more immersive, what with being able to see each and every one of our reactions in real time (with our own faces). Some users from rabbit didn't like this option, so maybe an option to toggle constantly showing profile pictures. This is just a thought since I don't really know how hard it would be to code this sort of thing. I would also like to extend some gratitude for all the work you guys/gals are putting into this streaming option.

**Comment by samuelmaddock** [comment]
Hi, thanks for requesting this.

> This is just a thought since I don't really know how hard it would be to code this sort of thing.

It is a challenging feature to add. The challenge comes from dealing with the amount of bandwidth required to send to everyone in the session. The more users, the more bandwidth needed. When more bandwidth is involved, the cost grows too.

I don't have plans to implement this at the moment, but it might be possible some time in the future.

> Part of the rabbit UI was that the profile pictures of everyone was visible to everyone during the stream

This might be something I could add in the future. If you don't mind, could you make another issue request specifically for this?
