### ISSUE TITLE
Allow Location

### ISSUE THREAD

**Issue by xPixieQueen** [samuelmaddock/metastream#128]
I have a Hulu Live account, and therefor it will not allow me into my account unless I allow location in my browser - which i cannot do in Metastream as of now. And although my browser itself has location available, the browser in metastream does not get effected by that. 

![image](https://user-images.githubusercontent.com/52554845/60695250-b29e7680-9ea6-11e9-8a90-f7de04af37dd.png)

**Comment by samuelmaddock** [comment]
Hi, thanks for reporting this bug. I should be able to provide a fix for this soon. In the meantime, you can login to Hulu in another tab in your browser. When you return to Metastream, you should be logged in.

**Comment by xPixieQueen** [comment]
Thank you much!! Your work means a lot
