### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by evant** [samuelmaddock/metastream#13]
As far as I can tell, there's nothing native specific here right? Just needs to be built and packaged? I can help.

**Comment by evant** [comment]
No update, documented as much as I could in the #linux-discussion channel on the discord.

**Comment by samuelmaddock** [comment]
@c-edw This is going to be stalled until switching back to Electron instead of using a fork. You can follow progress on issue #1

**Comment by samuelmaddock** [comment]
Linux will be supported when #94 is completed. It should be possible to try out the web app in its current state, albeit without networking support.
