### ISSUE TITLE
Ability to show chat at the side instead of as an overlay

### ISSUE THREAD

**Issue by LavenderTheGreat** [samuelmaddock/metastream#131]
Possible duplicate of (#18) but _much_ more specific.

The ability to put the chat box in a more standard place ie the right side of the screen beyond the media much like Twitch and Youtube (For premiers and livestreams) do. An example is below.

![image](https://user-images.githubusercontent.com/34808998/60731852-80415780-9f40-11e9-979c-a97b5ee83874.png)

**Comment by samuelmaddock** [comment]
https://github.com/samuelmaddock/metastream/releases/tag/v0.3.11
