### ISSUE TITLE
Hulu

### ISSUE THREAD

**Issue by galenc1a** [samuelmaddock/metastream#132]
Hulu does not load videos. It plays the parental advisory but then stops there.

- Metastream Version:
- Browser + Version:
- OS Version:

Steps to Reproduce:

1. Load hulu.com and interact.
2. Try to play any video and it stops short of playing your video. Goes blank after the rating before the show.

**Comment by samuelmaddock** [comment]
What's happening is Metastream picks up on the parental advisory intro and thinks _that's_ the video you want to watch. So when it ends, it skips to the next media in the queue.

I'll see what I can do to fix this.

**Comment by samuelmaddock** [comment]
Fixed in v0.3.12 https://github.com/samuelmaddock/metastream/releases/tag/v0.3.12
