### ISSUE TITLE
Black screen and no sound when joining

### ISSUE THREAD

**Issue by dnlmlr** [samuelmaddock/metastream#138]
## Description
When joining a lobby (as non host) with either an old video in it (from last time using the lobby), or a video already playing, you get a black screen without sound. The video progress can be seen and it is possible to skip in time, but the only way to get it working again is for the person experiencing the issue to skip the video. If the host or somone else skips, it does not work either. Sometimes it also recovers just by skipping around in the video timeline when the video is paused. This is does not work every time though.

## Versions
- Metastream Version: Beta 0.3.12 
- Browser + Version: Firefox 67.0.4 and multiple versions before, also Chrome 75.0.3770.100
- OS Version: Windows 10 1903 & 1809

## Steps to Reproduce:
1. Create lobby
2. Add and start a videos (tested with youtube)
3. Join the lobby on a different browser
4. The newly joined gets a black screen and no sound instead of the video

**Comment by samuelmaddock** [comment]
I just looked into this and it was actually pretty easy to reproduce. Thanks for the detailed report. 🙇 

It seems like it's a problem with browsers disabling video autoplay with sound. For Firefox you can change this setting in the address bar which fixes it.
![firefox_2019-07-07_19-03-39rGpW](https://user-images.githubusercontent.com/1656324/60774957-2f6d6280-a0ea-11e9-9f20-486db0ade45c.png)

There might be a way I can detect this error and notify the user of the problem. I'll leave this issue open until I look into it.

**Comment by dnlmlr** [comment]
Oh damn. I feel pretty stupid right now for not thinking to check that.
I just checked and I can confirm that allowing autoplay fixes the issue.
I also could bypass the problem by just pausing and playing on the non-host now every time. While that makes sense for this explanation, I am like 80% sure that this did not work some time ago (just to keep in mind).

Allowing autoplay sound fixes the issue in chrome as well, but chrome does not seem to prompt the user when joining like described. You have to manually go to the website settings menu and allow it there.

The log in chrome showed that at least in chrome the call to [ `media.play()`](https://github.com/samuelmaddock/metastream/blob/8df26976e3be7525c987de9a1c043923723e9a02/packages/metastream-remote-extension/src/player.js#L257) results in an uncaught promise when this issue occours.

In firefox I get the error `NotAllowedError: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.` in the log but no javascript debug trace or anything.

Anyways if you look into it you will find out the same things I just wrote in like 2 minutes but I'll still drop this in here. An error on `media.play` with conditions might be a way to detect this.

**Comment by samuelmaddock** [comment]
> An error on media.play with conditions might be a way to detect this.

Yep, I'm working on this now. I'm going to display a message in chat mentioning autoplay settings when the error is detected.

To mitigate the problem, muting the video and calling `play()` allows it to resume on YouTube (without sound). This is a much better experience since the user just needs to change their volume to fix it.

**Comment by samuelmaddock** [comment]
It's a bit verbose, but I've added a notice that will appear in the next update.
![chrome_2019-07-07_20-21-52fZ8i](https://user-images.githubusercontent.com/1656324/60775895-a3613800-a0f5-11e9-86db-7673202c031c.png)
