### ISSUE TITLE
Amazon Prime video playback issue

### ISSUE THREAD

**Issue by sidnotsyd** [samuelmaddock/metastream#140]
Tried to stream Good Omens on Amazon Prime but when I clicked play the video became very narrow and while the video itself played fine, it wouldn't return to the right aspect ratio until i exited the player. This didn't happen on any other website that I tried it with, but I had the same issue with other content on the same website. Tried to refresh the page and restarted the stream itself but still had the same issue.

**Comment by samuelmaddock** [comment]
Fixed
