### ISSUE TITLE
Most Media Wont AutoPlay

### ISSUE THREAD

**Issue by Kylerh15** [samuelmaddock/metastream#141]
- Metastream Version: Beta 0.3.10
- Browser + Version: Google Chrome 75.0.3770.100
- OS Version: Windows 10

Description:
So i wasnt sure to classify this as a bug or feature request but the problem im having is when attempting to add a movie to media on almost any 3rd party streaming site it will just show the website with the play button so all users have to enter interact mode to hit play this sometimes also causes desync.

Steps to Reproduce:
1. Play a video on almost any movie streaming site, Stream.cr, Openload, ect..
2. Watch as all users must enter interact mode to hit play at the same time

**Comment by LavenderTheGreat** [comment]
Could you specify the list of sites you are having trouble with? It's much easier to pinpoint issues with proper urls.

**Comment by Kylerh15** [comment]
yeah so every 3rd party movie streaming site ive tried so far has had this issue
these are the only ones i use fairly often that i can list.
https://scr.cr/home.php
https://lookmovie.ag/
https://openloadmovies.bz/
https://ololo.to/

**Comment by samuelmaddock** [comment]
Going to close this in favor of #178

**Comment by samuelmaddock** [comment]
@Kylerh15 autoplay has been improved with the latest version of the extension, please try again and let me know how it goes.
