### ISSUE TITLE
Media playback stuck on Twitch stream, won't move to next object in list

### ISSUE THREAD

**Issue by talethaphi** [samuelmaddock/metastream#142]
- Metastream Version: 0.3.13
- Browser + Version: Vivaldi 2.4.1488.35 
- OS Version: Mac OSx

Steps to Reproduce:

1. Loaded up Twitch and selected an online stream to share.
2. After Twitch stream was over, the browser stayed on the same page, despite several items were in the queue and clicking on "push to top".
3. Tried to get into "browser mode" to get out of video and move manually to the next site, layout of the video only allowed to click on other twitch streams by the same user and not get out of that particular site
4. There was no "abort current media" or "move to the next media" option to forcibly end the "session" on twitch, stuck there forever
5. Closed and reopened browser, same issue
6. Cleared history and cookies, same issue
7. Uninstalled and reinstalled Google Chrome extension, same issue

**Comment by LavenderTheGreat** [comment]
Have you tried the the button on the bottom bar out of interact mode which looks like the following to get to the next video in the playlist?

![image](https://user-images.githubusercontent.com/34808998/61408208-69ebb200-a8d7-11e9-8430-34ea54e235ad.png)

That should solve your 'abort current media' problem, however, there's still a problem that when twitch streams end you don't move to the next item in the playlist.

**Comment by talethaphi** [comment]
Thank you! It's a shame that twitch streams do seem to stay stuck on metastream, but hey, at least there's a choice to skip that I had apparently never seen before. 
Thanks again, man.
