### ISSUE TITLE
Client version mismatch

### ISSUE THREAD

**Issue by Bibbibibbi** [samuelmaddock/metastream#143]
Hello! I was watching a tv series with my friend and suddenly this happenned, I don't know what it is ):  Please help us!
![image](https://user-images.githubusercontent.com/52732513/60942888-dc420e00-a2a9-11e9-8f33-608a1e329fa5.png)

**Comment by samuelmaddock** [comment]
Someone in your session is using an older version of Metastream. Ask everyone to refresh and update if needed. It should be fixed then.
