### ISSUE TITLE
Ads keep appearing

### ISSUE THREAD

**Issue by AkinaFair** [samuelmaddock/metastream#148]
Whenever I am watching anime on crunchyroll with a friend. He keeps seeing ads pop up whenever I am playing the video. but I am not ever getting any on my end.

**Comment by LavenderTheGreat** [comment]
Make sure you are both using Crunchyroll's paid plan or an ad blocker. Metastream syncs players unlike stuff like rabb.it does.

**Comment by AkinaFair** [comment]
Ironic thing is I have the premium membership and I have an ad blocker/

**Comment by samuelmaddock** [comment]
@AkinaFair Metastream doesn't stream what you're seeing on your screen. The webpage loads on everyone's individual browser. There is no virtual browser like in Rabbit.

**Comment by AkinaFair** [comment]
So even if the person doesn't have the ad blocker or premium membership it will still show up?

**Comment by samuelmaddock** [comment]
It's the same experience as if that person went to the Crunchyroll video page in its own tab. The difference is that Metastream will detect the video and sync up the time to everyone in the session.

To get rid of ads, everyone in the session will either need a premium subscription or ad blocker.

**Comment by AkinaFair** [comment]
Hmm ok. Now All of a sudden I'm having an issue with playback now. Anytime I start the video it doesn't load right for anyone else watching. WTF

**Comment by samuelmaddock** [comment]
Is this still on Crunchyroll? Did you add the specific webpage for the video to the session?

For example, you should add something like https://www.crunchyroll.com/fruits-basket/episode-14-thats-a-secret-786971 instead of just https://www.crunchyroll.com/
