### ISSUE TITLE
Amazon video zoomed out

### ISSUE THREAD

**Issue by bruhwizard** [samuelmaddock/metastream#156]
- Metastream Version:
- Browser + Version:
- OS Version:

Steps to Reproduce:

1.find video
2.attempt to play

Amazon video is zoomed out with an incorrect aspect ratio.

**Comment by LavenderTheGreat** [comment]
Can you please fill out the form? It would allow us to solve the problem much more efficiently.

**Comment by SuweyStreams** [comment]
It works if you watch from Firefox with this problem, just not chrome.

**Comment by gbhojraj** [comment]
Also, using the "Interact" mode makes the video full screen for the duration of the mode. Exiting out goes back to the incorrect ratio (Chrome)

**Comment by gbhojraj** [comment]
Actually, it looks like if you go to the Prime Video page and start the video via Interact, it retains the correct ratio. This seems like a good workaround.

**Comment by samuelmaddock** [comment]
In the next update I'll be adding an option to toggle the auto-fullscreen feature which can be used as a temporary solution for this issue.
https://discordapp.com/channels/417584997533483009/491462012556279808/607773490833129472

**Comment by samuelmaddock** [comment]
Should be fixed now.
