### ISSUE TITLE
Hide non-video content

### ISSUE THREAD

**Issue by Mithril-Leaf** [samuelmaddock/metastream#157]
The ability to hide all content that is not the video source on a webpage would be quite useful when dealing with webpages that display content on the same web page as the video. Currently sites such as kimcartoon, solarmovies, etc. possess some of the webpage displayed alongside the video unlike with sites such as YouTube where only the video is displayed. 

![image](https://user-images.githubusercontent.com/28542270/62306762-6ff19f00-b450-11e9-822d-6caeb786d9ce.png)
![image](https://user-images.githubusercontent.com/28542270/62306782-754ee980-b450-11e9-9b79-07abc6b53e44.png)

Would it possible for metastream to simply mask the content on the website that is not the video source so that when the aspect ratio does not match the media source it will still only show the video.

**Comment by samuelmaddock** [comment]
Added in https://github.com/samuelmaddock/metastream/releases/tag/v0.4.0
