### ISSUE TITLE
Consider supporting local video files

### ISSUE THREAD

**Issue by inprealpha** [samuelmaddock/metastream#16]
A lot of us use local files and it will be great to be able to watch them together. I don't think it should be that difficult, maybe check if all participants are using the same file and then play the files together?

**Comment by samuelmaddock** [comment]
Right now I'd like to focus on improving the experience of streaming media. Someday I might get around to local file support, but for now I'd recommend trying existing tools like [Syncplay](https://syncplay.pl/).

**Comment by inprealpha** [comment]
Understandable, feel free to close this issue (though it was more like a request than an issue tbh).

**Comment by allsey87** [comment]
Regarding transcoding media format for use in a browser environment, perhaps the [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm) project could be a solution here?
