### ISSUE TITLE
vlive.tv and kshow123.net support

### ISSUE THREAD

**Issue by bangchans** [samuelmaddock/metastream#160]
Hello, I am a new user who has been using metastream for two days now and it's until now a pleasant experience, but I have a suggestion for two websites that aren't really working when I try to use them through metastream, which are vlive.tv and kshow123.net. The issue for vlive is that I can open the video but it only plays 9 seconds of the streams and that's it. As for the other website (kshow123) it won't even open. So I hope this message will help me be able to open these two websites because me and my friends use them a lot and when we are streaming on metastream we always want to watch stuff on them. Thank you in advance.

**Comment by samuelmaddock** [comment]
vlive should work now. kshow123 doesn't support https so they'll need to upgrade their infrastructure.
