### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by bangchans** [samuelmaddock/metastream#161]
Hello, I am a new user who really likes metastream so far, but I have noticed some stuff that would make metastream more amazing if they existed. 

Adding sound notifications when someone in the room says something, adding time stamps and also showing when a user is typing would be really appreciated. 

Thank you so much, in advance.

**Comment by samuelmaddock** [comment]
Hi, thanks for the suggestions! Would you mind creating an individual issue for each request you have?
