### ISSUE TITLE
Viki Subtitle Misalignment

### ISSUE THREAD

**Issue by Danimono** [samuelmaddock/metastream#166]
When viewing videos through Viki subtitles are miss aligned towards the right causing subtitle cut off. Subtitles properly align themselves to center in interact mode and will play centralised  until the next subtitle is triggered outside of interact mode.

- Metastream Version: 0.3.17
- Browser + Version: Firefox 68.0.1 (64-bit)
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Start up session and open a video from https://www.viki.com/ 
2. Allow video to play for a while and the subtitle misallignment should occur.
3. Switching to interact mode and allowing video to play can display the centralised subtitles when outside of the session.

**Comment by samuelmaddock** [comment]
This ended up being an issue with auto-fullscreen which was resolved in #309
