### ISSUE TITLE
Goggle 

### ISSUE THREAD

**Issue by ReiRchan** [samuelmaddock/metastream#168]
The goggle option doesn't work at all, you can look stuff up but you can't watch anything you look up on Google. At most, you can only look at photos, but they're no point if the other person can't see if you can't control the screen Like Rabbit use to offer.

**Comment by samuelmaddock** [comment]
The point of the Google option is to allow users to more easily navigate to another website within the Metastream media browser.

e.g. Search for VRV on Google, navigate to a video on VRV, and press Add To Session.
