### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by hazre** [samuelmaddock/metastream#17]
I just find out this program and its amazing. I know u could do something similar with vlc player but only with actual video links and not whole web sync.
~~Anyway I wanted to ask if you could add a adblock feature. especially for muting video ads.~~ (didnt know it supports chrome extensions)
Another thing is to have link invites instead of codes. And also for public rooms, make something similar to plugdj or rabbit. where you can see a lot of rooms and you can just join any public room to watch with anyone. Also could you please add a chat customization? like so you can move it somewhere else of the screen, toggle it off, add custom backdrop to make it more readable and etc.

Thanks for the work tho, its amazing thing for small or even big communities that want to watch things together.

**Comment by samuelmaddock** [comment]
In the future, please make a new GitHub issue for each individual request you have.

For adblockers, you can [install some Chrome Extensions using this guide](https://github.com/samuelmaddock/metastream/blob/master/docs/extensions.md). It's not a great user experience at the moment, but it mostly works. I've tried this with [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) and had some success.

Link invites is something I'd like to get around to. Maybe something like `https://getmetastream.com/invite/${friendCode}`. Which could guide new users to installing the app.

I'm personally trying to run as few backend services as possible to avoid costs of running a free project. I'm hoping to get access to [Discord Lobbies](https://discordapp.com/developers/docs/game-sdk/lobbies) as a way to provide public server listing. Still waiting to hear back though.

Can you make a new GitHub issue for chat customization? That would be a good way to track it.

Thanks for your feedback!

**Comment by samuelmaddock** [comment]
I'm going to close this issue since it's a collection of requests. Please make new issues for individual requests.
