### ISSUE TITLE
User and Queue Side Toggle

### ISSUE THREAD

**Issue by Danimono** [samuelmaddock/metastream#171]
I think an addition of side bar toggles to User and Queue overlays similar to the current chat box would be beneficial for those who want to reduce overlays over the viewing area (and accidentaly keep mouse overing like myself).

They could potentially be toggled to position above the chat in the right side bar. This would ideally include some minimise functionality to collapse the modules into header bars when not in use freeing up chat space. Very rough illustration below incase my description isn't clear. 

![MetastreamSuggestion](https://user-images.githubusercontent.com/53587420/62380225-aeff1d80-b540-11e9-9d10-3acbf7f7efa9.jpg)

**Comment by samuelmaddock** [comment]
Users and Next Up overlays are now moved to the sidebar in v0.10.0
https://twitter.com/GetMetastream/status/1279578958040793088

Actually ended up somewhat close to your design.
