### ISSUE TITLE
Crunchyroll doesn't upscale natively

### ISSUE THREAD

**Issue by LavenderTheGreat** [samuelmaddock/metastream#172]
- Metastream Version: Beta 0.3.17
- Browser + Version: Brave Version 0.67.123 Chromium: 76.0.3809.87 / Chrome 75.0.3770.142
- OS Version: Windows 10

Crunchyroll has a fullscreen option which as of now isn't used by Metastream, this makes it upscale a lower res version of the video you are viewing, regardless of the set quality on Crunchyroll. Notable side effects include standard blurring and subtitles becoming a lot harder to read.

A solution is to switch to fullscreen in interact mode, however this is temporary. Potentially a way to automatically click the fullscreen button could be implemented? (I'm not entirely sure about the feasibility of it).

Steps to Reproduce:

1. Go to Crunchyroll and select any episode from the shows listing
2. Add to queue
3. The video will be blur-ily upscaled when it should be fullscreen-ed with the option in the player.

Thanks to **Cartonet**  in the Discord for helping me to further find the issue and clarify it.

**Comment by samuelmaddock** [comment]
There might not be a solution for this unless I was able to switch back to Electron where it's possible to fullscreen a video without changing the window size. Going to leave this as `wontfix` for now.

**Comment by samuelmaddock** [comment]
This seems to work a bit better now since their HTML5 player upgrade. Quality automatically changes to 1080p after a short time. I won't be able to fix the blurry subtitles though.
