### ISSUE TITLE
Nicovideo support

### ISSUE THREAD

**Issue by kyokuP** [samuelmaddock/metastream#173]
Hello, I want to report an issue that occured with videos from http://nicovideo.jp,
the autoplay seems broken to every guest on the stream. I'm asking if it's possible to fix that and improve the support for niconico on Metastream.

Test URLs:
https://www.nicovideo.jp/watch/sm35464449
https://www.nicovideo.jp/watch/sm34789804
https://www.nicovideo.jp/watch/sm32564698

**Comment by samuelmaddock** [comment]
Hey @kyokuP, this is a common issue that comes up. Please see #178 for more info.

**Comment by samuelmaddock** [comment]
Autoplay, with a short delay, appears to be working now using v0.4.0 of the Metastream Remote extension.
