### ISSUE TITLE
Mega.nz Support

### ISSUE THREAD

**Issue by code403** [samuelmaddock/metastream#174]
Hello, Could you add Mega.nz support ? as of right now links don't even open

Working playback controls:
- [ ] Play/pause
- [x] Seek
- [x] Volume

Test URLs:
https://mega.nz/embed#!2WRkSQTK!mTiKHSL9ihbCeUtsYe5U2Nr8R4FOwxWAKQ82GZNp7z4

**Comment by LavenderTheGreat** [comment]
I recommend editing the checklist part of the body to untick the boxes, since videos don't play at all. As of now, it shows a 3/3 on the issue tracker when it's more like 0/3.

**Comment by samuelmaddock** [comment]
Looks like the requests for metadata about the URL were taking a very long time to resolve. In the next update I'll add a timeout for fetching metadata. This should at least allow the link to be added in a reasonable time.

**Comment by samuelmaddock** [comment]
@code403 mega.nz links will now load in Metastream, but the Mega video player needs some work. There's no autoplay detection and pausing doesn't work.

**Comment by code403** [comment]
thanks

**Comment by samuelmaddock** [comment]
Autoplay and pausing now works with the embedded player.
