### ISSUE TITLE
thewatchcartoononline.tv

### ISSUE THREAD

**Issue by KeeshPop** [samuelmaddock/metastream#176]
Name:
@keesh pop#5605 on Discord
About: 
      this website me and a close one use frequently seems to not work on metastream, and I was wondering if that could be worked out, because the service is wonderful so far!

Working playback controls:
- [ ✅] Play/pause
- [ ] Seek
- [✅ ] Volume

Test URLs:
https://www.thewatchcartoononline.tv/

Here’s an image of the console:

![](https://media.discordapp.net/attachments/606930140592734208/606931601682595943/Screenshot_2019-08-02_at_3.28.50_PM.png)

**Comment by samuelmaddock** [comment]
This websites has code which prevents it from being embedded in an `iframe`. You'd need to consult the website owner to ask them to remove said code.
