### ISSUE TITLE
Completely stuck on my Metastream

### ISSUE THREAD

**Issue by HeroicDefender97** [samuelmaddock/metastream#182]
I am stuck on this page and can't search up new pages on Metastream 

How do I get out of it? 

![2019-08-06](https://user-images.githubusercontent.com/53856950/62608852-b28efd80-b8ce-11e9-83d6-acd6a02103d5.png)

**Comment by LavenderTheGreat** [comment]
You seem to have added the entire website to the queue when you should've added just the video page ie. https://youtube.com/watch?v=bYCbm469Zq0 instead of https://youtube.com . To get off the page you can use the button that looks like ⏭️.
