### ISSUE TITLE
why dose youtube not work anymore

### ISSUE THREAD

**Issue by Jerm1129** [samuelmaddock/metastream#183]
why does youtube does not work anymore for the mod and can it be add back to the mod

**Comment by LavenderTheGreat** [comment]
Can you please use the template provided? It's also working perfectly fine on https://app.metastream.com .

If you are talking about the Gmod mod, it is currently not in development as far as I know so if Youtube is broken in it now you will have to just live with it or use an unofficial fork, if it exists.

I haven't tested YouTube in the legacy standalone app recently but compatibility with Youtube was available when I tested it last.
