### ISSUE TITLE
Synchronization with things that don't automatically play. 

### ISSUE THREAD

**Issue by NajiDang** [samuelmaddock/metastream#185]
An issue I've noticed is that with most sites when multiple users play media it doesn't actually synchronize their watching experiences. 
-Anon1 might press play and be at 4:25,
- Anon1 would tell Anon2 to interact with the page and press the same button in order to start the video and synchronize time timestamps. 
-In actuality, Anon2 would just be watching said video from the beginning while the external time stamp that Anon1 is using to navigate through the video is still continuing from 4:25 and so on. 

Essentially what I may have failed to bring to light is that I'm requesting that the admin of each room have the ability to continuously affect what the members of the room view, so that viewing experiences are actually synchronized. 
Also that you further test the workability of Metastreams ability to synchronize timestamps in different website styles and video servers. 
----I understand that this is probably almost practically screen sharing, and you have no actual plans to implement that now. I feel like you've already come more than halfway there. Most of your users will probably originate from Rabb.it, they'll be hoping for a very similar experience that still works through browsers. What you have has the potential to be far greater than whatever Kast(Rabb.it's WIP alt) could be. So don't stop here Sam! I'm a fan of how far Metastream has come so far

**Comment by samuelmaddock** [comment]
Hey, thanks for the support! As for the autoplay issue, I'm mostly tracking that in #178. I'd appreciate it if you made a new issue or revised this one to include a list of websites that aren't syncing properly.

**Comment by NajiDang** [comment]
Generally all _sorta_ illegal streaming sites for like movies, tv shows and/or anime. Examples being europixhd.net and gogoanime.tv. I could always chart more if it pleases you.

**Comment by samuelmaddock** [comment]
I made some improvements in the latest version of the Metastream Remote extension (v0.4.0). Let me know if autoplay is working better now.
