### ISSUE TITLE
I just checked out the official site for this and have questions

### ISSUE THREAD

**Issue by VaasKahnGrim** [samuelmaddock/metastream#191]
So first I want to say thank you so much for making this, it means alot since rabb.it died recently and me and my gf have been trying to find a replacement for our movie nights and this is pretty much what we are going to use now.

However I have a few questions that I'm not sure of atm. when I tested it with a youtube video I noticed that it already had me logged into youtube on the menu for it. Does everybody see that screen or is it only me? I would think alot of people wouldn't want others suddenly seeing every thing on their front page.

Second question, is there a way for making permanant accounts? like say Steam login or email registrations? if not then could that qualify as a feature request? I'd deffinitly be using this for feature showcasing to staff on a project of mine or for community movie nights.

**Comment by samuelmaddock** [comment]
Many of your questions are answered by the [FAQ](https://github.com/samuelmaddock/metastream/wiki/FAQ), I'd recommend reading it first. I'd recommend joining the Discord community for general questions like this.

> Second question, is there a way for making permanant accounts?

Not yet, but your session URL will only be usable by your browser with no account required.

If you have future feature requests, please create a new issue for each request and check that there are no duplicates before doing so please.
