### ISSUE TITLE
Netflix is not loading at all, i can't share anything on hulu, and only youtube and crunchyroll are working seemlessly so far.

### ISSUE THREAD

**Issue by marymendo** [samuelmaddock/metastream#194]
- Metastream Version:
- Browser + Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by marymendo** [comment]
I love where this is going, I used to be a user of rabbit before metastream. However, Netflix refuses to load, when I go to share something on hulu my friend can't see anything and pausing and playing it does not work, lastly the only sites working without issue are youtube and crunchyroll which would be great if my friend liked anime... but they don't. Anyway keep up the good work and please fix these issues so I can stay in touch with my friend who is hundreds of miles away.

**Comment by LavenderTheGreat** [comment]
Hello, would you mind filling out the body of the top post? It'll help us reproduce the issue. Also, if there's any error codes on Netflix and Hulu, please list them too.

Last but not least, it'd be really useful if you could split Netflix and Hulu into two separate issues, if you need help you can dm me in the Metastream Discord. 

-LTG

**Comment by samuelmaddock** [comment]
See #111, #135
