### ISSUE TITLE
123movies.la not loading

### ISSUE THREAD

**Issue by h6rus** [samuelmaddock/metastream#196]
This website does not work on Metastream. A completely gray screen covers the entire background, and the only way to get rid of it is to skip it. 
The website is: https://www3.123movies.la/123movies

**Comment by samuelmaddock** [comment]
This website has a script which is preventing it from being embedded into other websites. The only way to work around this might be to implement a popup player which plays content in another window.

**Comment by samuelmaddock** [comment]
I'm going to close this issue since the solution is tracked in the other ticket.

**Comment by h6rus** [comment]
Yeah, alright. Mind if you could elaborate on that last bit? What do you
mean by implementing a popup player playing from another window? Sorry, I'm
not a tech expert.

Thanks

**Comment by samuelmaddock** [comment]
@h6rus this website should work now starting with v0.6.0
