### ISSUE TITLE
Add popup player

### ISSUE THREAD

**Issue by samuelmaddock** [samuelmaddock/metastream#197]
Add a mode for playing content in a popup window.

Some websites won't work when embedded into app.getmetastream.com due to the website checking if it's the top frame (`window.top === window.self`). Neither of these properties are re-configurable and thus can't be overwritten to bypass the check.

A popup player presents new UX challenges and inconveniences.
- The Metastream UI can't overlay the new window.
- Interact mode would be enabled by default, but manipulating the website player wouldn't update Metastream.
- Chat wouldn't be easily accessible unless it could also be moved into a popup window.

**Comment by gurupras** [comment]
Just an FYI, a similar issue occurs when websites try to do something like `window.domain = ...` I believe

**Comment by samuelmaddock** [comment]
Released in v0.7.0
