### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by hazre** [samuelmaddock/metastream#20]
something similar to rabb.it's reacting emojis on the bottom that pops up on the whole screen.

**Comment by Kraballa** [comment]
I am thoroughly against the idea of reactions that pop up anywhere else than the chatroom itself. I had many issues with people spamming them which is distracting at best and extremely annoying at worst. If such a feature makes it into the final build please oh please create an option to disable it. This is one of my main issues with that site.
