### ISSUE TITLE
thewatchcartoononline.tv doesn't work :(

### ISSUE THREAD

**Issue by chickenoodle** [samuelmaddock/metastream#205]
https://www.thewatchcartoononline.tv here's the link! whenever i paste it into the search bar, it just 404's.

**Comment by LavenderTheGreat** [comment]
You sure you have the correct URL? Also next time it'd be preferable if you could use the available template for bug reporting to give us more info on the surrounding conditions.

The site may also not want to be embed into something like metastream, however most sites put proper errors out for this.

**Comment by samuelmaddock** [comment]
Duplicates #110
