### ISSUE TITLE
animeheaven.ru

### ISSUE THREAD

**Issue by akarixlove** [samuelmaddock/metastream#210]
Working playback controls:
- [x ] Play/pause
- [ ] Seek
- [ x] Volume

Test URLs:

https://animeheaven.ru/watch/fruits-basket-2019-sub.90651?ep=153967

The site doesn't seem to work with mini browsers like Opera.

**Comment by samuelmaddock** [comment]
It takes some time to load, but seems to work now. I don't plan to support Opera Mini.
