### ISSUE TITLE
Disney+ support

### ISSUE THREAD

**Issue by Lagbar** [samuelmaddock/metastream#225]
Is Disney+ available for use? I am using a Mac with Google Chrome and I am able to access all other websites other than disneyplus.com when using Metastream.

![Screen Shot 2019-11-18 at 1 04 51 PM](https://user-images.githubusercontent.com/57920520/69093801-15cb1880-0a04-11ea-86d1-281378f96d9d.png)

The screen turns black and doesn't respond. Disney+ works in my other tabs. I am under my school's wifi at the moment but I'm using a VPN (HotSpot Shield) that gives me access to every website that I have found. Is there no access from the website or is there a problem on my end?

Thanks!

**Comment by samuelmaddock** [comment]
Not yet, but hopefully soon when #197 is released. The Disney+ website prevents itself from being embedded in other websites which causes it to become a black screen.

**Comment by samuelmaddock** [comment]
@Lagbar I published an update to the Metastream Remote extension which adds support for Disney+. Check that it's up to date (extension version 0.4.0) and try again.

**Comment by Lagbar** [comment]
This worked a charm! Thank you so much! I was still figuring out how the synchronization worked on both ends of those in your room, but I think I've figured it out. Thanks again!
