### ISSUE TITLE
Metastream old session playing at start

### ISSUE THREAD

**Issue by Niebianin** [samuelmaddock/metastream#227]
Hello. I have been experiencing the following issue for past two days. I'll present it in a list of what has happened to keep it clear:

1. On Monday I joined a friend's stream. She was checking how metastream works. She played a long youtube video and we left the stream after seeing that everything works for her.

2. On Tuesday I wanted to start a stream. When I clicked on "start session", the youtube video started to play. I am marked as the Admin of the session, but I cannot skip the video.
Refreshing won't help. Closing the browser won't help. Deleting cache and cookies won't help. I can't turn the playing video off in any way.

3. I could join another person's stream without any issues.

4. Today, on Wednesday, again I wanted to start  a session and again I'm hit by the youtube video from point 1. New media links can be added to the queue, but I have no way to watch them with the other video playing.

**Comment by ExoTixWereWolf** [comment]
You should be able to hit the "Next" button next to the "play" button.

**Comment by Niebianin** [comment]
> 
> 
> You should be able to hit the "Next" button next to the "play" button.

There's only "add media" button. It looks like when you first start session, but new added videos move to the queue instead.

**Comment by ExoTixWereWolf** [comment]
> > You should be able to hit the "Next" button next to the "play" button.
> 
> There's only "add media" button. It looks like when you first start session, but new added videos move to the queue instead.

When you can add media to queue, you should be able to go next to the play button in the bottom left, and to the right of it. a next button. Hit that

**Comment by ExoTixWereWolf** [comment]
> > You should be able to hit the "Next" button next to the "play" button.
> 
> There's only "add media" button. It looks like when you first start session, but new added videos move to the queue instead.

You can also try finding a video you wanna watch but dont select it, right click it and click the option to add to metastream

**Comment by Niebianin** [comment]
![New Canvas](https://user-images.githubusercontent.com/58009026/69278392-86c82700-0be2-11ea-9486-c519cda89ef4.png)
Let me show you how it looks for me. I added media and the button won't appear. The friend's video is still playing.

**Comment by ExoTixWereWolf** [comment]
> ![New Canvas](https://user-images.githubusercontent.com/58009026/69278392-86c82700-0be2-11ea-9486-c519cda89ef4.png)
> Let me show you how it looks for me. I added media and the button won't appear. The friend's video is still playing.

Try what i stated above. Close meta and find a video you wanna watch and right click it and choose the metastream option. It should take priority. Normally clearing cookies and cache can fix it but an extension update came out as well. You may need to go update the extension or remove and re add it

**Comment by Niebianin** [comment]
> 
> 
> > ![New Canvas](https://user-images.githubusercontent.com/58009026/69278392-86c82700-0be2-11ea-9486-c519cda89ef4.png)
> > Let me show you how it looks for me. I added media and the button won't appear. The friend's video is still playing.
> 
> Try what i stated above. Close meta and find a video you wanna watch and right click it and choose the metastream option. It should take priority. Normally clearing cookies and cache can fix it but an extension update came out as well. You may need to go update the extension or remove and re add it

Okay, this one worked for me! Thank you

**Comment by samuelmaddock** [comment]
@Niebianin Thanks for reporting this! I wasn't able to reproduce the issue through interacting with the app, but I forced it into the bugged state and added a fix to ensure it doesn't happen.

**Comment by samuelmaddock** [comment]
Found a way to reproduce this which was consistent with the original post. Basically this can happen when the browser shuts down abruptly with Metastream still open in a tab. It won't have time to save its state properly for restoring at a later point. I've added a few that will go out in the next update.
