### ISSUE TITLE
Idea: add option to hide user list and bottom video bar

### ISSUE THREAD

**Issue by Asirex** [samuelmaddock/metastream#229]
I'd like to make a request to add an option to both hide the user list, and video bar, through the three vertical dots on the bottom right. You could for instance reduce the bottom bar to only the 3 vertical dots when you opt to hide it, and it would be very easy to pull it up again as the 3 dots will still be there. I am aware that the user list, bottom bar, and playlist disappear when your mouse doesn't move for a couple of seconds but I personally still find it bothersome when you accidentally make all of them show again because you accidentally moved your mouse

**Comment by samuelmaddock** [comment]
Users and Next Up overlays are now moved to the sidebar in v0.10.0
https://twitter.com/GetMetastream/status/1279578958040793088
