### ISSUE TITLE
Remembering accounts 

### ISSUE THREAD

**Issue by ontarri0** [samuelmaddock/metastream#235]
Could remembering accounts or any other way to not have to allow the same people join the session be possible in the future? I think it would be a good improvement.

**Comment by ExoTixWereWolf** [comment]
> Could remembering accounts or any other way to not have to allow the same people join the session be possible in the future? I think it would be a good improvement.

There is a settings option within meta for you to disable to have to allow or disallow a user.

While in a session click on the settings in the bottom right of the UI of meta
Go to session and set it to public instead of private

**Comment by ontarri0** [comment]
> > Could remembering accounts or any other way to not have to allow the same people join the session be possible in the future? I think it would be a good improvement.
> 
> There is a settings option within meta for you to disable to have to allow or disallow a user.
> 
> While in a session click on the settings in the bottom right of the UI of meta
> Go to session and set it to public instead of private.
> 
> Currently there is no accounts, its just usernames that aren't tied to anything except cache/cookies of the web browser. That would require More cost and maintenance for Sam, which i believe is he wishing to avoid since he works on it alone

Wont anyone be able to join then? Or do they still need the invite link?

**Comment by ExoTixWereWolf** [comment]
> > > Could remembering accounts or any other way to not have to allow the same people join the session be possible in the future? I think it would be a good improvement.
> > 
> > 
> > There is a settings option within meta for you to disable to have to allow or disallow a user.
> > While in a session click on the settings in the bottom right of the UI of meta
> > Go to session and set it to public instead of private.
> > Currently there is no accounts, its just usernames that aren't tied to anything except cache/cookies of the web browser. That would require More cost and maintenance for Sam, which i believe is he wishing to avoid since he works on it alone
> 
> Wont anyone be able to join then? Or do they still need the invite link?

You'd still have to send them an invite link

**Comment by ontarri0** [comment]
> > > > Could remembering accounts or any other way to not have to allow the same people join the session be possible in the future? I think it would be a good improvement.
> > > 
> > > 
> > > There is a settings option within meta for you to disable to have to allow or disallow a user.
> > > While in a session click on the settings in the bottom right of the UI of meta
> > > Go to session and set it to public instead of private.
> > > Currently there is no accounts, its just usernames that aren't tied to anything except cache/cookies of the web browser. That would require More cost and maintenance for Sam, which i believe is he wishing to avoid since he works on it alone
> > 
> > 
> > Wont anyone be able to join then? Or do they still need the invite link?
> 
> You'd still have to send them an invite link an if someone you don't want in your session has a previous one, just clear you cache files and meta will generate a new link when you send them to people

alright, thank you a lot for your help!
