### ISSUE TITLE
Choosing initial display name redirects to main app page instead of the referer

### ISSUE THREAD

**Issue by jaruba** [samuelmaddock/metastream#240]
- Metastream Version: 0.6.1
- Browser + Version: Chrome 79.0.3945.130
- OS Version: OSX (High Sierra) 10.13.6

Steps to Reproduce:

1. Open this URL in Incognito mode:
https://app.getmetastream.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D3EgpMgxRvxA

2. You are met with a page asking for a display name, enter a value and press "get started"

3. You are redirected to https://app.getmetastream.com/

Expected behavior:
It should redirect to the initial URL instead of the main app page.

We were testing a new feature in Stremio that presumed adding a video player context menu link to Metastream for shared viewing, but met this unpleasant UX issue that might cause much user confusion.

**Comment by samuelmaddock** [comment]
Thanks for reporting this @jaruba. I'll take a look this week.

**Comment by samuelmaddock** [comment]
@jaruba I released the update with this fixed just now. Should be good to go now, sorry about the delay!
