### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by kathelynn** [samuelmaddock/metastream#242]
If possible, please integrate Discord in Metastream so that we can have our profile picture and username including emotes if #241 gets implemented. Then allow us so we could easily send links via Metastream. Also, allow it so we could lock the session to users logged in on Discord only. Thankssssss

**Comment by samuelmaddock** [comment]
The legacy desktop version of Metastream had [Discord support with invites](https://github.com/samuelmaddock/metastream#legacy-desktop-app). If the desktop version were to ever return, this feature would come with it.
