### ISSUE TITLE
Netflix Pop-Up Issue

### ISSUE THREAD

**Issue by Vaciera** [samuelmaddock/metastream#254]
Unable to load Netflix properly.

Troubleshot with all "Meta stream isn't working" options.

Logging into Netflix makes you go back to the login screen, and netflix.com embed is pushed to popup which does not work (screen freezes, unable to interact with it, does not sync with others).

**Comment by thegh0sty** [comment]
Experiencing the same problem. It might be something Netflix has done, sadly..

**Comment by samuelmaddock** [comment]
To browse for content from netflix, you'll need to browse in a new tab, then copy the link into Metastream. I'll improve this user experience soon, likely by removing the netflix link to avoid confusion.

**Comment by samuelmaddock** [comment]
v0.10.0 now includes a much better experience for Netflix
https://twitter.com/GetMetastream/status/1279578958040793088
