### ISSUE TITLE
Hulu Problems

### ISSUE THREAD

**Issue by antiiyou** [samuelmaddock/metastream#262]
I'm having tremendous issues logging into Hulu through Metastream. I am logged in in my browser, tried adding it through the remote, it won't play or let me log in, just shows the info page and nothing else. It worked just before the most recent update, I'm really tired of this site constantly breaking as I only rely on this for me and a long distance friend since Rabbit has closed its doors. Hopefully this can be fixed soon, and not disabled.

**Comment by samuelmaddock** [comment]
Could you try using the popup player and let me know if that works? What's likely causing problems are the changes to browser cookies introduced in Chrome v80. I don't have a Hulu subscription to confirm at the moment.

![chrome_2020-03-13_19-44-42Bajr](https://user-images.githubusercontent.com/1656324/76714684-ebae0c80-66fe-11ea-9bed-80a401401e7a.png)

**Comment by vonny3492** [comment]
When watching on hulu, when you get to a commercial it thinks the video is over. I also don't have those pop up options

**Comment by samuelmaddock** [comment]
These issues should be resolved now with the latest extension version.
