### ISSUE TITLE
New Feature: mobile remote?

### ISSUE THREAD

**Issue by marv3lls** [samuelmaddock/metastream#263]
Basically, when I connect my mobile device (iPhone XR in my case) to the link that can't run the extension I just wanna be able to play & pause playback on it. Maybe fast-forward rewind too but simply play/pause would be great!

**Comment by samuelmaddock** [comment]
The browser extension is unfortunately what enables these features. It's possible to use the extension on Mobile Firefox for Android, but there's no solution for iOS. Sorry.
