### ISSUE TITLE
[Feature Request] - Video Chat

### ISSUE THREAD

**Issue by jasonkolodziej** [samuelmaddock/metastream#264]
Having the ability to use video chat if wanted. 

As a user, I would like the ability to have video/audio chat to see and or hear the reactions of others in the chat room. There would be the ability to mute oneself, as well as, administrative properties to even allow this feature in a chat session.

I believe this would allow for a more engaging user experience, especially for those students that would like to watch movies with their friends during this world pandemic (COVID-19). I am a senior at Texas A&M University studying Computer Science. I love the work you have done so far and would make certain that your application would become heavily recognized. 

`- Much Support & Best of Health -`

`Jason K.`

**Comment by samuelmaddock** [comment]
Please refer to #127. It's possible I may reconsider in the future, but for now I'm not actively looking to develop this feature.
