### ISSUE TITLE
Netflix Pop-Up Issue 

### ISSUE THREAD

**Issue by harshaface** [samuelmaddock/metastream#274]
Netflix opens in a new pop-up window on my browser (Chrome 80.0.3987.162), which, I don't mind, except that the video's playback controls, the chatbox and the rest of the Metastream UI are not in this popup as well. It was really confusing to use the first time and it's a major inconvenience right now. I got off of Netflix Party to use Metastream because of its availability on other services and this makes me want to go back to Netflix Party.

I hope that this is possible to implement a solution like Netflix Party's and while I haven't used any other service like Hulu or Crunchyroll (I've used it so far for 9anime which is smooth enough), I hope the same issue doesn't exist for them too.

And as a general suggestion: dark mode everything. Thank you guys for making this awesome application. It's helping me get through the quarantine one day at a time.

**Comment by samuelmaddock** [comment]
v0.10.0 now includes another popup to have chat side-by-side with Netflix
https://twitter.com/GetMetastream/status/1279578958040793088
