### ISSUE TITLE
Nothing but Youtube works

### ISSUE THREAD

**Issue by maddmesh** [samuelmaddock/metastream#278]
Using firefox on mac nothing but youtube worked for me last night 

- Metastream Version: .8.1_1
- Browser + Version: Firefox 74.0.1
- OS Version: 10.15.3

Steps to Reproduce:

1. Create playlist with videos from youtube, hulu, netflix, etc.
2. Only youtube will play

**Comment by samuelmaddock** [comment]
Make sure the extension has access to run on all sites.
https://github.com/samuelmaddock/metastream/wiki/FAQ#metastream-isnt-working
