### ISSUE TITLE
Please send chat notifications, when tab is in running in background

### ISSUE THREAD

**Issue by nandanraj56** [samuelmaddock/metastream#282]
Please send chat notifications (browser level, Same as whatsapp do), when tab is in running in background.
Suppose I am listening to some music sometimes other user sends chat messages, But I was not on meta tab, So I won't notice it, Is there any way to enable notification?
Only sound wont work as we wont notice it while music is playing. Please add browser level notifiacation, So that we can also see msg in browser popup, same as whatsapp do

**Comment by samuelmaddock** [comment]
Closing in favor of #298
