### ISSUE TITLE
Hulu Video Terminating After Discretion Warning

### ISSUE THREAD

**Issue by anne125** [samuelmaddock/metastream#285]
- Metastream Version: Beta 0.8.1_1
- Browser + Version: Firefox and Chrome
- OS Version: 

Steps to Reproduce:

1.
2.

**Comment by sberglin** [comment]
Same issue.

- Metastream Version: Beta 0.8.1_1
- Browser + Version: Chrome Version 81.0.4044.113
- OS Version: macOS Catalina 10.15.4

**Comment by samuelmaddock** [comment]
I should have a fix for this in the next update.

**Comment by samuelmaddock** [comment]
This should be fixed now in v0.9.0
