### ISSUE TITLE
Updating "display name" notifies chat of every character change

### ISSUE THREAD

**Issue by djpowers** [samuelmaddock/metastream#289]
- Metastream Version:  `Beta 0.8.1_1`
- Browser + Version: Firefox 76, Chrome 81
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Click settings during an in-progress session
2. Begin typing inside the "Display name" field

Each additional character change is broadcast in the chat as a "`display name` is now known as" notification So adding or deleting ten characters will result in ten messages being posted to the chat.

Ideally, I think the name change should not be posted to the chat until the preference window is closed. Alternatively, there could be a delay so it only posts after there has been no key input for some number of seconds.

**Comment by samuelmaddock** [comment]
Gooood catch. This is a regression introduced in the most recent update, I misunderstood how React hooks worked. I'll fix this in the next update.
