### ISSUE TITLE
Able to add non-video links to a playlist

### ISSUE THREAD

**Issue by mtag438** [samuelmaddock/metastream#291]
Browser: Vivaldi 2.11.1811.52 (Stable channel) (64-bit) 
OS: Windows 10 OS Version 1909 (Build 18363.778)

Steps:
1. Start a Metastream session
2. Add a link with no video content to a stream (ex. www.wikipedia.com)

Expected Result:
Links to sites which do not have streaming or video content should be ignored or display a message stating that the site is not a video site. 

Actual Result
The non-video link can be added to the playlist. Would it be possible to filter out non-video links?

**Comment by samuelmaddock** [comment]
Unfortunately it's not possible to always detect whether a video will be present on the page prior to loading it in a session. For example, sometimes it will require interacting with the page to begin playback. This is a fairly common case as well.

I think for now it's best if the host either skips the content or locks the queue to prevent it from being added.
