### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by TJDouble05** [samuelmaddock/metastream#297]
hi is there any extensions for opera browser? im mainly using opera on my pc but i have to use chrome everytime i want to use metastream.

**Comment by ExoTixWereWolf** [comment]
> hi is there any extensions for opera browser? im mainly using opera on my pc but i have to use chrome everytime i want to use metastream.

opera has an extension which lets you  install chrome extensions into opera

**Comment by TJDouble05** [comment]
> > hi is there any extensions for opera browser? im mainly using opera on my pc but i have to use chrome everytime i want to use metastream.
> 
> opera has an extension which lets you install chrome extensions into opera

OMG thank you! i didnt know this. youre amazing
