### ISSUE TITLE
Disable Media streaming / Join session as Chat-only client

### ISSUE THREAD

**Issue by crishaddad** [samuelmaddock/metastream#301]
It would be great to be able to join the stream "chat only", without playing the video; This would be great for people using dual devices. 

Example:
- I have a HTPC connected to my TV playing the Metastream media full-screen, with chat hidden.
- I join the session on my phone,  disable media streaming, and use the second session exclusively for chat.

[ Thanks to @samuelmaddock and all other contributors for a great piece of software by the way; I really, _REALLY_ like it. ]

**Comment by crishaddad** [comment]
Additionally, if this feature existed, it would be great to be able to access it via a parameter in the URL, so the 2 links can be distributed separately.

e.g. 
https://app.getmetastream.com/join/SESSION_ID
vs 
https://app.getmetastream.com/join/SESSION_ID?chat_only=true

**Comment by samuelmaddock** [comment]
I worry about implementing something like this and it causing confusion for others who could enable it by accident. I'll leave this open to see if anyone else has interest in this.

**Comment by samuelmaddock** [comment]
I'm going to close this issue for now. While I do realize the value it would add for you, it's another feature I'll need to maintain going forward which I'd like to avoid.
