### ISSUE TITLE
No subtitles on Amazon Video

### ISSUE THREAD

**Issue by jimhawk7** [samuelmaddock/metastream#303]
- Metastream Version: 0.8.1_1
- Browser + Version: Google Chrome 81.0.4044.129
- OS Version: Windows 10

Steps to Reproduce:

1. Add a show to queue (ex. https://www.amazon.com/gp/video/detail/B073S2612X/)
2. Queue to play manually or with autoplay.
3. When queued to play, subtitles do not display. However, subtitles are present if selected in interact mode, but returning to playback does not display them.
![Made in Abyss no subs](https://user-images.githubusercontent.com/64716043/80896627-6f778480-8cbe-11ea-9f78-98daf2045123.png)
![Made in Abyss subs on](https://user-images.githubusercontent.com/64716043/80896628-70101b00-8cbe-11ea-82a8-113b86c6a58a.png)

**Comment by Roycs** [comment]
I have the same problem tell me if it's solved

**Comment by Roycs** [comment]
I solved the problem by disabling the theater mode tell me if this worked for you

**Comment by Roycs** [comment]
Apparently it works but not every time for exemple for me The Hobbit works but not for Lost

**Comment by Roycs** [comment]
Try also to disable the auto-full screen it worked for me

**Comment by samuelmaddock** [comment]
As @Roycs mentioned, Theater Mode can unfortunately cause soft subtitles to be hidden. Make sure that's disabled and it should fix the issue.
