### ISSUE TITLE
Add playlist more easily

### ISSUE THREAD

**Issue by Roycs** [samuelmaddock/metastream#305]
It could be helpful to add a YouTube playlist more easily by only putting the link of the YouTube playlist, instead of doing it manualy

**Comment by ExoTixWereWolf** [comment]
> It could be helpful to add a YouTube playlist more easily by only putting the link of the YouTube playlist, instead of doing it manualy

I believe it does. All you need to do is start the playlist and once the video loads copy that url to the session and add it. One video will load on queue but if you hit the next button, the next video comes up

**Comment by samuelmaddock** [comment]
^ Public YouTube playlists should work. Let me know if they don't and I'll reopen the issue.

**Comment by manuth** [comment]
Somehow it's not working anymore.
When adding a playlist to the session, all Metastream does is loading the landing page of YouTube.
