### ISSUE TITLE
Viki Support

### ISSUE THREAD

**Issue by mpostma3** [samuelmaddock/metastream#309]
Hi Sam, thanks so much for doing this! Watch parties have suddenly become very important to me and my family in this time of isolation. 

Would it be possible to add support for Viki? Right now I can add the link and it looks like it's trying to work, but it can't get past login to play the actual video. Once I hit "submit" it just goes blank, and then goes back to the login screen. 

 I can't find any other service that offers Viki support, so I don't know if it's possible, but if it is we'd really appreciate it! 

Thanks again, 

Miranda

**Comment by samuelmaddock** [comment]
Hi, could you please try this again using the latest Chrome extension version (0.4.2)?

**Comment by mpostma3** [comment]
You're phenomenal, that totally works! I can log in, the video plays beautifully, and other people can join the party no problem. The only thing now is that for some reason the subtitles aren't coming through. I do not have "Theater mode" on, but maybe there's some other setting I'm missing? 

Thanks again! 
Miranda

**Comment by samuelmaddock** [comment]
@mpostma3 are you able to share a link to a (preferably free to watch) video with the issue? Is it an issue for everyone in your session? Have you tried resizing your browser?

Normally this issue comes up when Theater Mode is enabled, but you mentioned you don't have that on.

**Comment by mpostma3** [comment]
Hi Sam,

Yeah, for sure! This one’s a link to a free-to-watch. I’ve put it on public, but it’s limited to 2 people for now.

https://app.getmetastream.com/join/e59bb514507a7bf9e5215c9da1d79f39809df86ce4bee70afa1d39a0da855f54

I’ve noticed that I can see the subtitles in interact mode, but they disappear when I leave interact mode. Maybe that’s a hint? Also, I’m on Mac if that makes a difference.

Thanks again for your work!

Miranda


On May 11, 2020, at 8:27 PM, Samuel Maddock <notifications@github.com<mailto:notifications@github.com>> wrote:



@mpostma3<https://github.com/mpostma3> are you able to share a link to a (preferably free to watch) video with the issue? Is it an issue for everyone in your session? Have you tried resizing your browser?

Normally this issue comes up when Theater Mode is enabled, but you mentioned you don't have that on.

**Comment by samuelmaddock** [comment]
I was able to figure out the issue and it should be fixed in the next Metastream Remote extension update (v0.5.3). 🎉
