### ISSUE TITLE
stuck on the same website, unable to leave even when restarting

### ISSUE THREAD

**Issue by shortasn** [samuelmaddock/metastream#314]
- Metastream Version: Beta 0.9.0
- Browser + Version: Chrome

I'm stuck on the same website, even when I restarted the session, created a new session, I even redownloaded chrome and metastream but every time I start the session the same website pops up, same for the other person and neither of us can do anything.

**Comment by Neptunus-Equester** [comment]
having the same issue here on both web and application, not sure if this has been addressed

**Comment by samuelmaddock** [comment]
Press the Next button on the playback bar until the queue is empty.

![image](https://user-images.githubusercontent.com/1656324/106376557-7ffb7f00-6364-11eb-9ff5-33bdc384c8d2.png)
