### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Taevoncnhii** [samuelmaddock/metastream#317]
My friend and I have been trying to watch a movie for about an hour now, but it seems Metastream wont play anything from the site we are trying to use. The site we are trying to use is called https://fmovies.to/  please help us figure this out. We really do like Metastream so far, its worked for other sites we've used but just not this one. Thank you so much for your time!! I hope you can get back to me soon.

**Comment by samuelmaddock** [comment]
Please try using the popup player as described in #197

The website fmovies.to has security measures in place which make it difficult to playback while embedded in the Metastream website. When using the popup player, it's no longer an issue.

**Comment by samuelmaddock** [comment]
See #280

In the next update, instructions will be more clear for using the popup player with fmovies.to. A chat will be included alongside the popup player as well.
