### ISSUE TITLE
Firefox and Crunchyroll: Blocked by Content Security Policy

### ISSUE THREAD

**Issue by jeffreymcclain** [samuelmaddock/metastream#322]
- Metastream Version: Beta 0.9.0 (Firefox add-on 0.4.1)
- Browser + Version: Firefox 77.0.1 (64-bit)
- OS Version: Windows 10 64-bit, v2004 (May 2020 Update)

Steps to Reproduce:

1. Perform a fresh install of the latest version of Firefox on Windows 10.
2. Install the [Metastream Remote add-on](https://addons.mozilla.org/en-US/firefox/addon/metastream-remote/)
3. Leave the default Firefox settings alone.
4. Login to Crunchyroll Premium.
5. [Attempt to start a Metastream session](https://i.imgur.com/j4itzGr.png).
6. The session fails to load with a "Blocked by content security policy" error.

Note: Several of my friends as well as other people have reported this issue on the Discord "support" channel, so I'm assuming it's just an issue with the latest Firefox update. Chrome still works fine with Crunchyroll, so it appears to be specific to Firefox.

**Comment by samuelmaddock** [comment]
I've uploaded a new version of the Firefox addon. It will be fixed after the Firefox addons team reviews the update.

In the meantime, a workaround would be to use the Popup player.

**Comment by jeffreymcclain** [comment]
I updated my Firefox add-on to 0.4.3 and just wanted to confirm that the issue appears to be fixed, thanks again!
