### ISSUE TITLE
Pop-up issue

### ISSUE THREAD

**Issue by miamia321** [samuelmaddock/metastream#325]
Every website seems to work fine but whenever I click Netflix, a pop-up screen comes up and it says that www.netflix.com is embed blocked so a pop-up browser is required. I don't understand what this means and it's kind of irritating since we cant chat or figure out how it works with multiple people. How do I fix it or make it go away?

**Comment by samuelmaddock** [comment]
This is a limitation of using Metastream with Netflix at the moment. I'm working on a feature now which will open a chat side-by-side with the Netflix window. I'll announce when it's ready on Discord/Twitter.

**Comment by samuelmaddock** [comment]
@miamia321 The v0.10.0 update includes a chat popup window to make this much easier.
https://twitter.com/GetMetastream/status/1279578958040793088

**Comment by miamia321** [comment]
I thought it was something with my own browser not by metastream itself. Thanks for letting me know
