### ISSUE TITLE
Crunchyroll playback does not work.

### ISSUE THREAD

**Issue by evrefurbished** [samuelmaddock/metastream#335]
Upon playing anything from Crunchyroll, the auto-fullscreen feature does not engage leaving the entirety of the Crunchyroll page visible. Upon entering Interact Mode to set it to fullscreen manually, it only produces a white screen for other viewers.

- Metastream Version: Beta 0.10.2
- Browser + Version: Chrome
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:
1. Attempt to play a Crunchyroll video in Metastream.
2. Use Interact Mode to enter full screen, then exit interact mode.

**Comment by samuelmaddock** [comment]
Using Interact Mode to enter fullscreen will only affect what you see in your local browser. Auto-fullscreen does almost the same thing, it zooms to fit the video within the window. However, it won't hide the rest of the page unless you also enable "Theater Mode."

It would be helpful to know which version of Chrome you have and a link to a video if these options aren't working for you.

![2020-07-22_16-53-17](https://user-images.githubusercontent.com/1656324/88227659-e8da9f80-cc3b-11ea-9e3c-bc87651945d0.gif)
