### ISSUE TITLE
Ethereum Swarm

### ISSUE THREAD

**Issue by pafubemi** [samuelmaddock/metastream#39]
Hi.
Is it possible to use Ethereum Swarm in your app? 
Do you support bzz:/ urls?

**Comment by samuelmaddock** [comment]
I'm not familiar with Ethereum Swarm, it looks like it's similar to IPFS? Metastream currently only works with traditional browser protocols (http, https, etc), but I'd be interested in someday supporting distributed protocols if they're easy to integrate.

This would likely be something I'd have to switch to official Electron before considering (#1).

**Comment by samuelmaddock** [comment]
Going to close this ticket for now unless further interest is shown. Metastream is moving to a web app so it might work if a Chromium or Firefox browser support it. Could be issues related to mixed-content though as the web app runs on an `https://` domain.
