### ISSUE TITLE
Got a error after dowloading

### ISSUE THREAD

**Issue by warsazk10** [samuelmaddock/metastream#40]
- Metastream Version: 0.1.4
- OS Version: Mac

When I downloaded Metastream on my new mac then out of know where this error pops up after downloading it

Error: 

dlopen(/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/node-67.node, 1): Library not loaded: @loader_path/libsodium.dylib
  Referenced from: /Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/node-67.node
  Reason: no suitable image found.  Did find:
	/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib: code signature invalid for '/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib'

	/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib: code signature invalid for '/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib'

    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:596:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at load (/Applications/Metastream.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:13:10)
    at /Applications/Metastream.app/Contents/Resources/app.asar/node_modules/sodium-native/index.js:1:186

**Comment by samuelmaddock** [comment]
Which version of macOS are you using? macOS 10.11 is the minimum required to run Metastream.

That said, I think I've seen this fixed by [installing `libsodium` via homebrew](http://macappstore.org/libsodium/). This should install any missing dependencies you might have.

**Comment by samuelmaddock** [comment]
Closing as this seemed to be fixed using the above solution.
