### ISSUE TITLE
Playing episode on Netflix

### ISSUE THREAD

**Issue by plGazela** [samuelmaddock/metastream#42]
- Metastream Version: Beta 0.1.4
- OS Version: Windows 10 Home 64-bit

After logging in to Netflix and selecting the series for example Big Mouth Metastream plays the trailer of the series instead of the episode. This error is in most series, but there are cases where the series is played normally for example Your lie in April.

![netflix](https://user-images.githubusercontent.com/44746554/47964257-5ba28200-e037-11e8-84b0-3024e7b82d2f.png)

**Comment by samuelmaddock** [comment]
This is fixed for the next release which should be out in the next couple days. If you want a fix now, you can try the prerelease here: https://github.com/samuelmaddock/metastream/releases/tag/v0.1.5
