### ISSUE TITLE
Chrome extension breaks cloudflare challenge

### ISSUE THREAD

**Issue by Sanceilaks** [samuelmaddock/metastream#451]
Steps to Reproduce:
1. Install extension 
2. Try to solve any [challenge](https://2captcha.com/demo/cloudflare-turnstile)

**Comment by TheSainEyereg** [comment]
Agree, I checked every extension that I have, and found that this problem occurs only with Metastream enabled

**Comment by khankul** [comment]
Just had it happen on Firefox too.

**Comment by themineraria** [comment]
Same here, on chrome and firefox, I can't access gitlab.com, the cloudflare challenge is unsolvable

**Comment by Sanceilaks** [comment]
Now it just works
