### ISSUE TITLE
Different key/Key bind for interaction mode

### ISSUE THREAD

**Issue by SuspiciousScout** [samuelmaddock/metastream#52]
A lot of video players will go out of full screen if you press escape, yet you also need to press escape to cancel out of Interact mode, so maybe this key can be changed or you can rebind it?

**Comment by samuelmaddock** [comment]
Yeah, this needs to be reworked. For now, you can leave the cursor idle to automatically exit interact mode.

**Comment by SuspiciousScout** [comment]
Okay, good to know. Keep up the good work with this software, by the way. I've been wanting to watch anime with my friends for the longest time and this makes it happen, so I really wanna see it nice, polished, and bug-free!

**Comment by samuelmaddock** [comment]
For the web app (#94), interact mode now adds a frame around embedded content which can be clicked to exit. However, the Metastream UI can no longer appear over top of fullscreened media. Auto-fullscreen zooms the page to fit media to the browser window, which I'm hoping will be sufficient.
