### ISSUE TITLE
App does not close when closing window on Mac

### ISSUE THREAD

**Issue by Juesto** [samuelmaddock/metastream#54]
- Metastream Version: Beta 0.2.2
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open app
2. Close window

Additional Observations:

Attempting to use view menu commands causes the following message: 
![image](https://user-images.githubusercontent.com/12691160/49467783-fa123680-f7e1-11e8-8bba-6fb1ed5ee90f.png)

**Comment by samuelmaddock** [comment]
Closing as the Electron app will soon be deprecated by #94.
