### ISSUE TITLE
disconnect error

### ISSUE THREAD

**Issue by hikomas** [samuelmaddock/metastream#72]
both internets are working fine but both ends keep getting disconnected. usually the person that joins the host. won't let you back into the session until you restart the session or switch whos hosting. beta 0.2.3

**Comment by samuelmaddock** [comment]
I'm creating #74 to track this. In the meantime, please consult the [Network Troubleshooting](https://github.com/samuelmaddock/metastream/wiki/Network-Troubleshooting) guide.
