### ISSUE TITLE
Youtube Blocked?

### ISSUE THREAD

**Issue by aweapingangel** [samuelmaddock/metastream#73]
Whether in the home screen or from google, Youtube refuses to load.  It just stopped working randomly and now does not load at all.  I've already tried restarting etc.

**Comment by samuelmaddock** [comment]
Hmm, have you tried in your primary browser as well? If you can post the URL as well, that might help.

**Comment by aweapingangel** [comment]
I have but it fails to load.  I get the error: there was an error
requesting (YouTube link)

**Comment by samuelmaddock** [comment]
Could you add the URL you tried requesting to this thread? Does it happen with every YouTube link?

**Comment by aweapingangel** [comment]
I do not remember the specific link but it happens with every link I try.
Even if I put in youtube.com it still can’t load it

**Comment by aweapingangel** [comment]
Ok so it’s working again.  I did switch to a different WiFi.  One theory I
have is that there is a sort of parental control device on that WiFi, but
the thing is Metastream was able to load YouTube on that same WiFi before
it stopped working.  And the program wasn’t blocked on either the WiFi or
the firewall... so I still don’t know what the issue with it was.
