### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by r4de** [samuelmaddock/metastream#79]
Hi Sam,
by trying to install metastream, I've got this error.

- Metastream Version: 0.2.3
- OS Version: Windows 7 (64)

An web/browser version would be cool ;)

![metastream-error](https://user-images.githubusercontent.com/43291428/54871220-0b8f4680-4db1-11e9-8823-4c2abfa36f9c.JPG)

**Comment by samuelmaddock** [comment]
See #14
