### ISSUE TITLE
Tubi TV bugged out

### ISSUE THREAD

**Issue by RoboSpongie** [samuelmaddock/metastream#80]
- Metastream Version: v0.2.3
- OS Version: Windows 10

The player worked fine for a bit until it reached a certain point then it made a error page like this symbol x _ x

Steps to Reproduce:

1. Pull up a Tubi TV movie
2. Watch movie at a certain point the player may crash

**Comment by samuelmaddock** [comment]
Seems to work okay in the web app (#94)
