### ISSUE TITLE
Update metastream download link on the website to 0.2.6

### ISSUE THREAD

**Issue by Tripater** [samuelmaddock/metastream#86]
Currently, the download button on the website gives you version 0.2.3, and not the latest 0.2.6. The version available on the website still has the Netflix error, which could drive potential users away (As it has happened with my friends, as they didn't know new versions were available on Github).

Steps to Reproduce:

1. Open https://getmetastream.com/
2. Click on any of the Download buttons (Both Windows and Mac are outdated).
3. You get 0.2.3

**Comment by samuelmaddock** [comment]
There was a regression in v0.2.4-v0.2.6 regarding establishing a network connection. I still need to figure out the root cause.

**Comment by Tripater** [comment]
Fair enough, thought it was just an oversight, sorry for opening an issue then.

**Comment by samuelmaddock** [comment]
No worries, thanks for looking out! I've definitely made this mistake before, but this time it was intentional. 🙂
