### ISSUE TITLE
Support for HTTP authentication

### ISSUE THREAD

**Issue by Protected** [samuelmaddock/metastream#87]
I'd like to be able to add (or browse) URLs behind HTTP authentication. Currently I'm getting a black screen.

**Comment by samuelmaddock** [comment]
This might be supported by the efforts in #94. You should be able to try it out in the currently available version of the web app.

If it doesn't work, it might be prevented by the iframe sandboxing policy I have in place.

**Comment by samuelmaddock** [comment]
This seems to work in the web app when I used this test page I found: https://jigsaw.w3.org/HTTP/Basic/
