### ISSUE TITLE
Failure to fit screen size when using fullscreen

### ISSUE THREAD

**Issue by frostwind8174** [samuelmaddock/metastream#9]
- Metastream Version: Beta 0.1.2
- OS Version: Windows 10 Pro, V 1803, Build 17134.228

Steps to Reproduce:

1. Maximize Metastream
2. Go fullscreen.
3. Click the Maximize Window button twice.
4. Exit fullscreen.
5. Minimize window.
6. Enter fullscreen.

Picture of issue: https://i.imgur.com/Ybo4xv6.png

Other notes: Despite going fullscreen, the taskbar does not disappear. It is also a 50/50 chance of replicating it perfectly every time, as it takes some playing around with fullscreen and minimizing/maximizing. It's a very strange bug, but others might wonder what is happening in the future.

**Comment by samuelmaddock** [comment]
Are you doing anything between steps 5 and 6? I haven't been able to reproduce the issue after a few tries.

**Comment by frostwind8174** [comment]
I am not. It's weird and triggers on some weird sequence. It might not have to be exactly two, could be more or less. It's very weird to trigger, but I found a generalization around twice.

**Comment by samuelmaddock** [comment]
Closing as the Electron app will soon be deprecated by #94. Also, I believe this issue was eventually fixed by  a Windows patch.
