### ISSUE TITLE
its invisible when i click to invite people

### ISSUE THREAD

**Issue by Koopax** [samuelmaddock/metastream#91]
- Metastream Version: Beta 0.2.3
- OS Version: Mac OS 10.11.6

Steps to Reproduce:

1. Starts a session
2. I can click invite but everything is invisible and glitched out but the video and the thing to change your videos and stuff is all still visible its just not easy as to what your looking at

**Comment by samuelmaddock** [comment]
Could you attach a screenshot so I can see what the issue looks like? I don't quite follow the problem.

**Comment by samuelmaddock** [comment]
Closing due to lack of information.
