### ISSUE TITLE
Twist.moe support

### ISSUE THREAD

**Issue by ExoTixWereWolf** [samuelmaddock/metastream#95]
Working playback controls:
- [x] Play/pause
- [x] Seek
- [x] Volume

Test URLs:

https://twist.moe/a/one-punch-man-2/1

I believe im fine running it. Youtube and various others work decently.  This site may have some different setup even though how minimal it looks. I do not know if there are other servers (you can't pick)

**Comment by samuelmaddock** [comment]
What isn't working with the site?

**Comment by ExoTixWereWolf** [comment]
> What isn't working with the site? You can request any URL in Metastream, it works with most websites by default.

Most videos have difficulty playing. Other sites work fine, but when trying to watch any on that site. i was given issues. Try it out and see if you have any for testing id guess (if you don't mind) It cpuld just be something on my side. Youtube played wondefully at 1080. i tried other streaming sites and they seemed to work fine as well
